models/voting_variant.py
from app import db
from sqlalchemy import Column, String, Integer, ForeignKey


class VotingVariant(db.Model):
    __tablename__ = 'voting_variants'

    id = Column(Integer, primary_key=True)
    voting_id = Column(Integer, ForeignKey('votings.id'))
    title = Column(String(255))
    description = Column(String(1000))

    voting = db.relationship('Voting')

routes/auth.py
from flask import Blueprint, current_app, redirect, render_template, request, url_for, session, render_template_string, flash
from flask_login import login_required, login_user, logout_user
from flask_babel import gettext

auth = Blueprint('auth', __name__)

@auth.route('/login')
def auth_login():
    # define return url
    return_url = request.args.get('next')
    if return_url and return_url[0] != '/':
        return_url = None

    return render_template('auth_login.html', return_url=return_url)

@auth.route('/auth/form/<auth_method>')
def auth_form(auth_method):

    # redirect
    if auth_method == 'vkontakte':
        auth_url = "%s/authorize?client_id=%d&redirect_uri=%s&scope=2" % (
            current_app.config['AUTH_VKONTAKTE_HOST'],
            current_app.config['AUTH_VKONTAKTE_APP_ID'],
            'http://%s/auth/vkontakte' % current_app.config['SERVER_NAME']
        )

    else:
        raise Exception('Wrong auth method')

    # define return url
    if 'return_url' in request.args:
        session['return_url'] = request.args.get('return_url')

    return redirect(auth_url)


@auth.route('/auth/<auth_method>')
def auth_check(auth_method):

    if auth_method == 'vkontakte':

        # get access token
        if 'code' not in request.args:
            flash(gettext('Error while authorize user'))
            return redirect('/')

        code = request.args['code']

        url = '/access_token?client_id=%d&client_secret=%s&code=%s&redirect_uri=%s' % (
            current_app.config['AUTH_VKONTAKTE_APP_ID'],
            current_app.config['AUTH_VKONTAKTE_SECRET'],
            code,
            'http://%s/auth/vkontakte' % current_app.config['SERVER_NAME']
        )

        import urllib2
        import json
        response = json.loads(urllib2.urlopen(current_app.config['AUTH_VKONTAKTE_HOST'] + url).read())

        # check user existence
        from models.user import User
        user_instance = User.query.filter_by(vkontakte_id=response['user_id']).first()

        # register
        if user_instance is None:
            from app import db
            user_instance = User(vkontakte_id=response['user_id'])
            db.session.add(user_instance)
            db.session.commit()

        # authorize
        if not login_user(user_instance):
            raise Exception('Error authenticating user')

    # return
    return_url = session.get('return_url') if session.has_key('return_url') else '/'
    return redirect(return_url)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect('/')

routes/vote.py
from flask import Blueprint, render_template, request, jsonify, current_app, redirect, session, url_for
from flask_login import current_user

vote = Blueprint('vote', __name__)


@vote.route('/vote/save/<voting_id>', methods=['POST'])
def vote_save(voting_id=None):

    response = {'error': 0}

    try:
        from models.voting import Voting
        from models.vote import Vote

        # get variants
        if 'variant[]' not in request.form:
            raise Exception('Variants not passed')

        voting_instance = Voting.query.get(voting_id)
        variant_id_list = voting_instance.filter_invalid_variants(request.form.getlist('variant[]'))

        # check permission to save
        if current_user.is_authenticated():

            # Check if user voted in this voting
            if Vote.query.filter_by(voting_id=voting_id, user_id=current_user.get_id()).first() is not None:
                raise Exception('User already voted in this voting')

            # save vote
            from app import db
            point = len(voting_instance.variants)
            for variant_id in variant_id_list:
                db.session.add(Vote(voting_id=voting_id, voting_variant_id=variant_id, point=point, user_id=current_user.get_id()))
                point -= 1

            db.session.commit()

            response['redirect_url'] = url_for('voting.voting_page', voting_id=voting_id)

        else:
            session['vote'] = {
                'voting_id': voting_id,
                'variants': variant_id_list
            }

            if 'auth_method' not in request.form:
                raise Exception('Auth method not specified')

            response['redirect_url'] = url_for('auth.auth_form',
                auth_method=request.form.get('auth_method'),
                return_url=url_for('vote.vote_session_save')
            )

    except Exception, e:
        response['error'] = 1
        response['errorMessage'] = str(e)

    return jsonify(response)


@vote.route('/vote/ses_save', methods=['GET'])
def vote_session_save():

    # check permission to save
    if not current_user.is_authenticated():
        raise Exception('Not allowed to save')

    # prepare vote
    from models.voting import Voting
    from models.vote import Vote

    # get variants
    if 'vote' not in session:
        raise Exception('Variants not passed')

    voting_id = session['vote']['voting_id']

    voting_instance = Voting.query.get(voting_id)
    variant_id_list = session['vote']['variants']

    # Check if user voted in this voting
    if Vote.query.filter_by(voting_id=voting_id, user_id=current_user.get_id()).first() is not None:
        return redirect(url_for('voting.voting_page', voting_id=voting_id))

    # save vote
    from app import db
    from models.vote import Vote
    point = len(voting_instance.variants)
    for variant_id in variant_id_list:
        db.session.add(Vote(voting_id=voting_id, voting_variant_id=variant_id, point=point, user_id=current_user.get_id()))
        point -= 1

    db.session.commit()

    return redirect(url_for('voting.voting_page', voting_id=voting_id))

routes/voting.py
from flask import Blueprint, render_template, render_template_string, request, jsonify, current_app, redirect, session, url_for, flash
from flask_login import login_required
from flask_babel import gettext

voting = Blueprint('voting', __name__)

"""
Voting list
"""
@voting.route("/")
def voting_list():

    from models.voting import Voting
    from sqlalchemy import or_

    query = Voting.query

    remote_address = request.remote_addr

    # filter votes not visible in current country
    if remote_address != '127.0.0.1':
        import pygeoip
        geoip = pygeoip.GeoIP('./configs/geoip/GeoIP.dat')
        alpha2 = geoip.country_code_by_addr(remote_address)

        query = query.filter(or_(Voting.country.is_(None), Voting.country == alpha2))

    # filter private votes, not owned by me
    from flask_login import current_user
    query = query.filter(or_(Voting.token.is_(None), Voting.owner_id == current_user.get_id()))

    return render_template('voting_list.html', voting_list=query.all())

"""
Voting editor
"""
@voting.route('/voting/new')
@voting.route('/voting/edit/<voting_id>')
@login_required
def voting_edit(voting_id=None):

    from models.voting import Voting
    if voting_id:
        voting_instance = Voting.query.get(voting_id)

        # check permissions to edit
        from flask_login import current_user
        if not voting_instance.is_moderated_by(current_user):
            raise Exception('You are not allowed to moderate this voting')
    else:
        from flask_login import current_user
        voting_instance = Voting(owner_id=current_user.get_id())

    # get country list
    from pycountry import countries

    return render_template('voting_edit.html', voting=voting_instance, countries=countries)


"""
Voting page
"""
@voting.route('/voting/<voting_id>')
@voting.route('/voting/<voting_id>/<token>')
@voting.route('/v/<voting_id>')
@voting.route('/v/<voting_id>/<token>')
def voting_page(voting_id, token=None):

    # get voting
    from models.voting import Voting
    voting_instance = Voting.query.get(voting_id)
    if voting_instance is None:
        return render_template('error_notfound.html'), 404

    # check privacy
    if not voting_instance.is_public() and voting_instance.token != token:
        return render_template('error_notfound.html'), 404

    from flask_login import current_user
    from models.vote import Vote

    # Show voting variants
    if not current_user.is_authenticated() or Vote.query.filter_by(voting_id=voting_id, user_id=current_user.get_id()).first() is None:
        if voting_instance.is_allowed_for_country():
            return render_template('voting_variants.html', voting=voting_instance, user=current_user)
        else:
            flash(gettext('This voting not allowed in your country. Allowed only for %s' % voting_instance.country))

    # Get points of variants
    from app import db
    from sqlalchemy.sql import func, label
    vote_stat_list = db.session\
        .query(Vote.voting_variant_id, func.sum(Vote.point).label('rate'))\
        .filter_by(voting_id=voting_id)\
        .group_by(Vote.voting_variant_id)\
        .order_by('rate DESC')\
        .all()

    # get variants
    voting_variants = voting_instance.variants

    # prepare structure
    votes = []
    total_points = 0
    for vote_stat in vote_stat_list:
        for variant in voting_variants:
            if variant.id != vote_stat[0]:
                continue
            votes.append({
                'variant': variant,
                'rate': vote_stat[1]
            })
            voting_variants.remove(variant)
            total_points += vote_stat[1]
            break

    for variant in voting_variants:
        votes.append({
            'variant': variant,
            'rate': 0
        })

    # calc total stat
    for vote in votes:
        vote['percent'] = round(vote['rate'] / total_points * 100, 2)

    return render_template('voting_result.html', voting=voting_instance, votes=votes)


"""
Save voting
"""
@voting.route('/voting/save', methods=['POST'])
@login_required
def voting_save():
    from models.voting import Voting
    from flask_login import current_user

    if request.form.get('id'):
        voting_instance = Voting.query.get(request.form.get('id'))

        # check permissions to edit
        if not voting_instance.is_moderated_by(current_user):
            raise Exception('You are not allowed to moderate this voting')
    else:
        voting_instance = Voting(owner_id=current_user.get_id())

    # name
    voting_instance.name = unicode(request.form['name'])

    # country
    if request.form.get('country'):
        voting_instance.country = unicode(request.form['country'])

    # privacy
    if request.form.get('privacy') == 'public':
        voting_instance.set_public()
        print 'pub'
    else:
        voting_instance.set_private()
        print 'priv'

    from app import db
    db.session.add(voting_instance)
    db.session.commit()

    flash(u'Voting successfully saved')
    return redirect(url_for('voting.voting_page', voting_id=voting_instance.id))

"""
New voting variant
"""
@voting.route('/voting/<voting_id>/new_variant')
@login_required
def variant_new(voting_id=None):

    # get voting
    from models.voting import Voting
    voting_instance = Voting.query.get(voting_id)

    # check owner
    from flask_login import current_user
    if current_user != voting_instance.owner:
        raise Exception('Not allowed to edit voting')

    # create variant
    from models.voting_variant import VotingVariant
    variant_instance = VotingVariant(voting_id=voting_id)

    return render_template('voting_variant_edit.html', variant=variant_instance)


"""
Edit voting variant
"""
@voting.route('/voting/edit_variant/<variant_id>')
@login_required
def variant_edit(variant_id=None):

    # get variant
    from models.voting_variant import VotingVariant
    variant_instance = VotingVariant.query.get(variant_id)

    # get voting
    voting_instance = variant_instance.voting

    # check owner
    from flask_login import current_user
    if current_user != voting_instance.owner:
        raise Exception('Not allowed to edit voting')

    return render_template('voting_variant_edit.html', variant=variant_instance)


"""
Save voting variant
"""
@voting.route('/voting/save_variant', methods=['POST'])
@login_required
def variant_save():

    from models.voting_variant import VotingVariant

    if request.form.get('id'):
        variant_instance = VotingVariant.query.get(request.form.get('id'))
    else:
        if 'voting_id' not in request.form:
            raise Exception('Voting not specified');

        variant_instance = VotingVariant(voting_id=request.form['voting_id'])

    variant_instance.title = request.form['title'].strip()
    variant_instance.description = request.form['description']

    from app import db
    db.session.add(variant_instance)
    db.session.commit()

    return redirect(url_for('voting.voting_page', voting_id=variant_instance.voting_id))

templates/auth_login.html
{% extends "empty_layout.html" %}
{% block title %} {{ _('Authorisation') }} :: {% endblock %}
{% block body %}
    <div style="margin-top: 200px; text-align: center;">
        <p>{{ _('Select authorization provider through which you would like to sign in').upper() }}:</p>
        {% if config.AUTH_VKONTAKTE %}
        <a href="{{ url_for('auth.auth_form', auth_method='vkontakte', return_url=return_url) }}" class="btn btn-default btn-social btn-social-vk">Вконтакте</a>
        {% endif %}
        {#
        <a href="javascript:void(0);" data-auth-method="facebook" class="btn btn-default btn-social btn-social-fb">Facebook</a>
        <a href="javascript:void(0);" data-auth-method="twitter" class="btn btn-default btn-social btn-social-twitter">Twitter</a>
        <a href="javascript:void(0);" data-auth-method="google" class="btn btn-default btn-social btn-social-google">Google</a>
        #}
    </div>
{% endblock %}

templates/error_notfound.html
{% extends "empty_layout.html" %}
{% block title %} {{ _('Page not found') }} :: {% endblock %}
{% block body %}
    <h1>{{ _('Page not found') }}</h1>
{% endblock %}

templates/voting_edit.html
{% extends "empty_layout.html" %}
{% block title %}{{ _('Edit voting') }} :: {% endblock %}
{% block body %}
<h1>{{ _('Voting editor') }}</h1>
<ol class="breadcrumb">
    <li><a href="{{ url_for('voting.voting_list') }}">{{ _('Votings') }}</a></li>
    <li>{{ voting.name|default(_('Add voting'), true) }}</li>
</ol>
<form method="post" action="{{ url_for('voting.voting_save') }}">
    <input type="hidden" name="id" value="{{ voting.id|default('', true) }}" />
    <div class="form-group">
        <label>{{ _('Name') }}</label>
        <input type="text" class="form-control" name="name" placeholder="{{ _('Voting name') }}" value="{{ voting.name|default('', true) }}" autocomplete="off">
    </div>
    <div class="form-group">
        <label>{{ _('Country') }}</label>
        <select class="form-control" name="country">
            <option value="">{{ _('All countries') }}</option>
            {% for country in countries %}
            <option value="{{ country.alpha2 }}"{% if country.alpha2 == voting.country %} selected="selected"{% endif %}>{{ country.name }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="form-group">
        <label>{{ _('Privacy') }}</label>
        <div class="radio">
            <label>
                <input type="radio" name="privacy" value="public" {% if voting.is_public() %}checked="checked"{% endif %} />
                {{ _('Visible for all') }}
                {% if voting.id and voting.is_public() %}
                <div class="bg-success" style="padding: 10px;">
                    <span class="glyphicon glyphicon-share"></span>
                    {{ _('Use this link to share') }}:
                    <a href="{{ voting.get_url() }}">{{ voting.get_url() }}</a>
                </div>
                {% endif %}
            </label>
        </div>
        <div class="radio">
            <label>
                <input type="radio" name="privacy" value="private" {% if not voting.is_public() %}checked="checked"{% endif %} />
                {{ _('Visible for all, who know link') }}
                {% if voting.id and not voting.is_public() %}
                <div class="bg-success" style="padding: 10px;">
                    <span class="glyphicon glyphicon-share"></span>
                    {{ _('Use this link to share') }}:
                    <a href="{{ voting.get_url() }}">{{ voting.get_url() }}</a>
                </div>
                {% endif %}

            </label>
        </div>
    </div>
    <div class="form-group">
        <input type="submit" value="{{ _('Save') }}" class="btn btn-success" />
    </div>
</form>
{% endblock %}

templates/voting_result.html
{% extends "empty_layout.html" %}
{% block title %} {{ voting['name'] }} :: {{ _('Voting results') }} :: {% endblock %}
{% block meta %}
<meta name="description" content="{{ voting['name'] }}. {{_('Leave your vote in on-line voting.') }}">
<meta property="og:type"   content="article">
<meta property="og:image" content="http://{{ config['SERVER_NAME'] }}/images/ico.png">
<meta property="og:title" content="{{ voting['name'] }}">
<meta property="og:url" content="http://{{ config['SERVER_NAME'] }}/voting/{{ voting['id'] }}">
<meta property="og:description" content="{{_('Leave your vote in on-line voting.') }}">
{% endblock %}
{% block body %}

    <div class="row">
        <div class="col-md-9">
            <ol class="breadcrumb">
                <li><a href="{{ url_for('voting.voting_list') }}">{{ _('Votings') }}</a></li>
                <li>{{ _('Voting results') }}</li>
            </ol>
        </div>
        <div class="col-md-3">
            <p class="bg-warning" style="padding: 8px 15px;">
                {{ _('Voted persons:') }} {{ voting.get_voted_users_num() }}
            </p>
        </div>
    </div>

    <h1>{{ voting['name'] }}</h1>

    {% if current_user.is_authenticated() and voting.owner == current_user %}
    <div class="btn-toolbar">
        <a href="{{ url_for('voting.variant_new', voting_id=voting.id) }}" class="btn btn-success btn-xs"><span class="glyphicon glyphicon-plus"></span> {{ _('Add variant') }}</a>
    </div>
    {% endif %}

    <div class="top-space bottom-space">
        <a href="http://vk.com/share.php?url={{ voting.get_url() }}" target="_blank" title="{{ _('Share at Vkontakte') }}"><img src="/images/social/vkontakte.png" /></a>
        <a href="https://www.facebook.com/sharer/sharer.php?u={{ voting.get_url() }}" target="_blank" title="{{ _('Share at Facebook') }}"><img src="/images/social/facebook.png" /></a>
        <a href="http://twitter.com/intent/tweet?text={{ voting['name'] + '. ' + _('Leave your vote in on-line voting.') + ' ' + voting.get_url() + ' %23EverVoter' }}" target="_blank" title="{{ _('Share at Twitter') }}"><img src="/images/social/twitter.png" /></a>
        <a href="https://plus.google.com/share?url={{ voting.get_url() }}" target="_blank" title="{{ _('Share at Google+') }}"><img src="/images/social/google.png" /></a>
    </div>

    {% for vote in votes %}
        {{ vote.variant.title }} ({{ vote.percent }}%)
        <div class="progress">
            <div class="progress-bar{% if vote.percent >= 30 %} progress-bar-danger{% elif vote.percent >= 20 %} progress-bar-warning{% elif vote.percent >= 10 %} progress-bar-info{% else %} progress-bar-success{% endif %}" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: {{vote.percent}}%;">
            </div>
        </div>
    {% endfor %}

    <div class="top-space bottom-space">
        <a href="http://vk.com/share.php?url={{ voting.get_url() }}" target="_blank" title="{{ _('Share at Vkontakte') }}"><img src="/images/social/vkontakte.png" /></a>
        <a href="https://www.facebook.com/sharer/sharer.php?u={{ voting.get_url() }}" target="_blank" title="{{ _('Share at Facebook') }}"><img src="/images/social/facebook.png" /></a>
        <a href="http://twitter.com/intent/tweet?text={{ voting['name'] + '. ' + _('Leave your vote in on-line voting.') + ' ' + voting.get_url() + ' %23EverVoter' }}" target="_blank" title="{{ _('Share at Twitter') }}"><img src="/images/social/twitter.png" /></a>
        <a href="https://plus.google.com/share?url={{ voting.get_url() }}" target="_blank" title="{{ _('Share at Google+') }}"><img src="/images/social/google.png" /></a>
    </div>

    {% if config['DISQUS'] == True %}
    <div id="disqus_thread"></div>
    <script type="text/javascript">
        var disqus_shortname = '{{ config['DISQUS_SHORTNAME'] }}';
        var disqus_identifier = '{{ voting['_id'] }}';
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
    {% endif %}

{% endblock %}

templates/voting_variant_edit.html
{% extends "empty_layout.html" %}
{% block title %}{{ _('Edit voting variant') }} :: {% endblock %}
{% block body %}
<h1>{{ _('Voting variant editor') }}</h1>
<ol class="breadcrumb">
    <li><a href="{{ url_for('voting.voting_list') }}">{{ _('Votings') }}</a></li>
    <li><a href="{{ url_for('voting.voting_page', voting_id=variant.voting_id) }}">{{ _('Voting') }}</a></li>
    <li>{{ variant.title|default(_('Add variant'), true) }}</li>
</ol>
<form method="post" action="{{ url_for('voting.variant_save') }}">
    {% if variant.id %}
    <input type="hidden" name="id" value="{{ variant.id }}" />
    {% else %}
    <input type="hidden" name="voting_id" value="{{ variant.voting_id }}" />
    {% endif %}

    <div class="form-group">
        <label>{{ _('Title') }}</label>
        <input type="text" class="form-control" name="title" placeholder="{{ _('Variant title') }}" value="{{ variant.title|default('', true) }}" autocomplete="off">
    </div>

    <div class="form-group">
        <label>{{ _('Description') }}</label>
        <textarea rows="6" class="form-control" name="description" placeholder="{{ _('Variant description') }}">{{ variant.description|default('', true) }}</textarea>
    </div>


    <div class="form-group">
        <input type="submit" value="{{ _('Save') }}" class="btn btn-success" />
    </div>
</form>
{% endblock %}

templates/voting_variants.html
{% extends "empty_layout.html" %}
{% block title %}{{ voting['name'] }} :: {% endblock %}
{% block meta %}
<meta name="description" content="{{ voting['name'] }}. {{_('Leave your vote in on-line voting.') }}">
<meta property="og:type" content="article">
<meta property="og:image" content="http://{{ config['SERVER_NAME'] }}/images/ico.png">
<meta property="og:title" content="{{ voting['name'] }}">
<meta property="og:url" content="http://{{ config['SERVER_NAME'] }}/voting/{{ voting['id'] }}">
<meta property="og:description" content="{{_('Leave your vote in on-line voting.') }}">
{% endblock %}
{% block body %}
{% if not user.is_authenticated() %}
<div class="modal" id="frmAuth">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">{{ _('Sign in') }}</h4>
            </div>
            <div class="modal-body">
                {% if config.AUTH_VKONTAKTE %}
                <a href="javascript:void(0);" data-auth-method="vkontakte" class="btn btn-default btn-social btn-social-vk">Вконтакте</a>
                {% endif %}
                {#
                <a href="javascript:void(0);" data-auth-method="facebook" class="btn btn-default btn-social btn-social-fb">Facebook</a>
                <a href="javascript:void(0);" data-auth-method="twitter" class="btn btn-default btn-social btn-social-twitter">Twitter</a>
                <a href="javascript:void(0);" data-auth-method="google" class="btn btn-default btn-social btn-social-google">Google</a>
                #}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">{{ _('Close') }}</button>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $('#frmAuth .modal-body a.btn-social').click(function(e) {
        $('#frmAuth').modal('hide');
        $('#frmVote')
            .data('auth-method', $(this).data('auth-method'))
            .submit();
    });
</script>
{% endif %}

<ol class="breadcrumb">
    <li><a href="{{ url_for('voting.voting_list') }}">{{ _('Votings') }}</a></li>
    <li>{{ voting['name'] }}</li>
</ol>

<h1>{{ voting['name'] }}</h1>

<div class="row-fluid top-space">
    <div class="col-md-6">
        <div class="panel panel-info">
            <div class="panel-heading">
                {{ _('Variants') }}
                {% if current_user.is_authenticated() and voting.owner == current_user %}
                    <div class="btn-toolbar pull-right">
                        <a href="{{ url_for('voting.variant_new', voting_id=voting.id) }}" class="btn btn-success btn-xs"><span class="glyphicon glyphicon-plus"></span> {{ _('Add variant') }}</a>
                    </div>
                {% endif %}
            </div>
            <ul id="variants" class="votingPanel list-group">
                {% for variant in voting.variants %}
                <li class="list-group-item">
                    <input type="hidden" name="variant[]" value="{{ variant.id }}"/>
                    <h4 class="list-group-item-heading">{{ variant.title }}</h4>

                    <p class="list-group-item-text">{{ variant.description }}</p>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <div class="col-md-6">
        <form id="frmVote" method="post" action="{{ url_for('vote.vote_save', voting_id=voting['id']) }}" data-auth-method="{{ user.is_authenticated() }}">
            <div class="panel panel-success">
                <div class="panel-heading">
                    {{ _('Vote') }}
                    <button type="submit" class="btn btn-danger btn-xs pull-right" style="display: none;">
                        <span class="glyphicon glyphicon-send"></span> {{ _('Vote') }}
                    </button>
                </div>

                <ul id="vote" class="votingPanel list-group">
                    <li class="list-group-item" id="lblDropPlaceMarker">{{ _('Place your vote here') }}</li>
                </ul>

            </div>
        </form>

        <div style="font-size: 12px;">
            <p class="bg-success" style="padding: 10px; margin: 10px 0;">
                <span class="glyphicon glyphicon-info-sign"></span>
                {{ _('Standard systems allow to choose just one option among several. Because of this majority vote may cause dissatisfaction for large part of respondents as their voice in fact not taken into account. If the winning option voted 40 percents of respondents thought that the other 60 is not included. So respondent will not vote for the most suitable option, but for the most traversed to get to the percentage of winners. This voting system allows you to build acceptable ratings , and get the winning result that will satisfy the most number of respondents. Each option of the rating assigned a score greater the higher the option in rating. The winner is not the option that received the most first places in the ranking, but the one that received the most amount of points.') }}
            </p>
            <p class="bg-success" style="padding: 10px; margin: 10px 0;">
                <span class="glyphicon glyphicon-ok"></span> {{ _('Drop variants in order of your favour') }}
            </p>
            <p class="bg-success" style="padding: 10px; margin: 10px 0;">
                <span class="glyphicon glyphicon-ok"></span> {{ _('Skip variants you don\'t want to vote for') }}
            </p>
        </div>
    </div>
</div>

<script type="text/javascript">
    // sort votes
    $("#variants, #vote")
    .sortable({
        connectWith: ".votingPanel",
        placeholder: 'drop-placeholder',
        helper: function(e, elem) {
            console.log(elem);
            return elem.clone().addClass('drag-helper');
        },
        update: function(e, ui) {
            if($('#vote li').length) {
                $('#frmVote button[type=submit]').show();
            }
            else {
                $('#frmVote button[type=submit]').hide()
            }

        }
    })
    .disableSelection();

    $('#vote')
        .on('sortover', function() {
            $('#lblDropPlaceMarker').remove();
        })
        .sortable("option", "cancel", "#lblDropPlaceMarker" );

    // send form
    $('#frmVote').submit(function(e) {
        e.preventDefault();
        var $frm = $(this);

        // check auth
        var authMethod = $frm.data('auth-method');
        if(authMethod === 'False') {
            // show login form
            $('#frmAuth').modal();
        } else if(authMethod === 'True') {
            // save vote for authorised user
            $.post($frm.attr('action'), $frm.serialize(), function(response) {
                if(response.error == 0) {
                    location.href = response.redirect_url;
                }
            }, 'json');
        } else {
            // save vote in session for unauthorised user
            $.post($frm.attr('action'), $frm.serialize() + '&auth_method=' + authMethod, function(response) {
                if(response.error == 0) {
                    location.href = response.redirect_url;
                }
            }, 'json');
        }

    })

</script>

{% endblock %}